DBrms/Models/Extended/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DBrms.Models.Extended
{
    [MetadataType(typeof(MetadataRestaurant))]

    public partial class Restaurant
    {


    }

    public class MetadataRestaurant
        {
        
        
        [Required(ErrorMessage = "Enter Name")]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Picture { get; set; }
        [Required]
        public Nullable<int> LocationId { get; set; }
        [Required]
        public string PopularMenu { get; set; }
        [Required]
        [DisplayName("Cost Range")]
        public string CostPerOrder { get; set; }
        [Required]
        public string Time { get; set; }
        [Required]
        public string Cuisine { get; set; }
        [Required]
        public string Extra { get; set; }
        [Required]
        public string Discount { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
  
        public Nullable<bool> IsActive { get; set; }
 
        public Nullable<bool> Visible { get; set; }
    }

}

DBrms/Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Foods = new HashSet<Food>();
            this.Reviews = new HashSet<Review>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Picture { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string PopularMenu { get; set; }
        [DisplayName("Cost Range")]
        public string CostPerOrder { get; set; }
        public string Time { get; set; }
        public string Cuisine { get; set; }
        public string Extra { get; set; }
        public string Discount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        [DisplayName("Active")]
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
        public virtual FoodOrder FoodOrder { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

DBrms/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBrms.Models;
using PagedList;
using PagedList.Mvc;

namespace DBrms.Controllers
{
    public class RestaurantsController : Controller
    {
        dbrmsEntities db = new dbrmsEntities();

        // GET: Restaurants
        public ActionResult Index(int? id)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            id = Convert.ToInt32(Session["RestaurantsId"]);

            List<Review> reviews = db.Reviews.Where(x => x.RestaurantsId == id).ToList();
            ViewBag.ReivewAll = reviews.Count();

            List<ReviewFood> reviewFoods = db.ReviewFoods.Where(x => x.Food.RestaurantId == id).ToList();
            ViewBag.ReivewFoodAll = reviewFoods.Count();

            List<FoodCart> foodCarts = db.FoodCarts.Where(x => x.Food.RestaurantId == id).ToList();
            ViewBag.FoodCarts = foodCarts.Count();

            List<FoodCart> foodDelivered = db.FoodCarts.Where(x => x.Food.RestaurantId == id && x.PaidAmount != null).ToList();
            ViewBag.FoodDelivered = foodDelivered.Count();

            List<Food> foods = db.Foods.Where(x => x.RestaurantId == id).ToList();
            ViewBag.FoddsTotal = foods.Count();



            List<Review> reviewstoday = new List<Review>();
            foreach (var item in db.Reviews.Where(x => x.RestaurantsId == id))
            {
                var datetoday = item.Date;
                DateTime daydate = Convert.ToDateTime(datetoday);
                string day = daydate.Date.ToString("yyyy-MM-dd");
                if(day==DateTime.Now.Date.ToString("yyyy-MM-dd"))
                {
                    reviewstoday.Add(item);
                }
            }
            ViewBag.ReivewToday = reviewstoday.Count();


            List<ReviewFood> reviewFoodsToday = new List<ReviewFood>();
            foreach (var item in db.ReviewFoods.Where(x => x.Food.RestaurantId == id))
            {
                var datetoday = item.Date;
                DateTime daydate = Convert.ToDateTime(datetoday);
                string day = daydate.Date.ToString("yyyy-MM-dd");
                if (day == DateTime.Now.Date.ToString("yyyy-MM-dd"))
                {
                    reviewFoodsToday.Add(item);
                }
            }
            ViewBag.ReivewFoodsToday = reviewFoodsToday.Count();



            List<FoodCart> foodCartsToday = new List<FoodCart>();
            foreach (var item1 in db.FoodCarts.Where(x=> x.Food.RestaurantId== id ))
            {
                var datetoday = item1.Cart.Date;
                DateTime daydate = Convert.ToDateTime(datetoday);
                string day = daydate.Date.ToString("yyyy-MM-dd");
                if(day==DateTime.Now.Date.ToString("yyyy-MM-dd"))
                {
                    foodCartsToday.Add(item1);
                }
            }
            ViewBag.FoodCartsToday = foodCartsToday.Count();


            List<FoodCart> foodDeliveredToday = new List<FoodCart>();
            foreach (var item in db.FoodCarts.Where(x=> x.Food.RestaurantId== id && x.PaidAmount != null))
            {
                var datetoday = item.Cart.Date;
                DateTime daydate = Convert.ToDateTime(datetoday);
                string day = daydate.Date.ToString("yyyy-MM-dd");
                if(day==DateTime.Now.Date.ToString("yyyy-MM-dd"))
                {
                    foodDeliveredToday.Add(item);
                }
            }
            ViewBag.FoodDeliveredToday = foodDeliveredToday.Count();

            
            
            return View();
        }



        public ActionResult Menu(int? id, int? page, string search)
        {


            id = Convert.ToInt32(Session["RestaurantsId"]);
            List<Restaurant> restaurants = db.Restaurants.Where(X => X.RestaurantId == id).ToList();
            ViewBag.Restaurants = restaurants;

            if (search != null)
            {
                return View(db.Foods.Where(x => x.Name.StartsWith(search)).ToList().ToPagedList(page ?? 1, 5));
            }



            return View(db.Foods.Where(x => x.RestaurantId == id).ToList().ToPagedList(page ?? 1, 5));


        }

        [HttpGet]
        public ActionResult MenuAdd()
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            int id = Convert.ToInt32(Session["RestaurantsId"]);
            return View();
        }
        [HttpPost]
        public ActionResult MenuAdd([Bind(Include = "Name,Image,Price,Details")] Food food, HttpPostedFileBase ImageFile)
        {

            

                String filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                String extension = Path.GetExtension(ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                food.Image = "/Image/" + filename;
                filename = Path.Combine(Server.MapPath("/Image/"), filename);
                ImageFile.SaveAs(filename);
                int id = Convert.ToInt32(Session["RestaurantsId"]);
                food.RestaurantId = id;
                db.Foods.Add(food);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Menu");

           
        }
        [HttpGet]
        public ActionResult MenuEdit(int? id)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }
        [HttpPost]
        public ActionResult MenuEdit([Bind(Include = "FoodId,RestaurantId,Name,Image,Price,Details")]Food food)
        {
           
                db.Entry(food).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Menu");
          
        }


        [HttpGet]
        public ActionResult MenuDelete(int? id)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View();
        }

        [HttpPost]
        public ActionResult MenuDelete(int id)
        {
            Food food = db.Foods.Find(id);
            db.Foods.Remove(food);
            db.SaveChanges();
            return RedirectToAction("Menu");
        }


        public ActionResult PopularMenu()
        {
            return View(db.Foods.ToList());
        }

        [HttpGet]
        public ActionResult PopularMenuAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PopularMenuAdd([Bind(Include = "Name,Image,Price,Details")] Food food, HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                String filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                String extension = Path.GetExtension(ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                food.Image = "/Image/" + filename;
                filename = Path.Combine(Server.MapPath("/Image/"), filename);
                ImageFile.SaveAs(filename);

                db.Foods.Add(food);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Newspanel");

            }
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            id = Convert.ToInt32(Session["RestaurantsId"]);

            return View(db.Restaurants.Where(x => x.RestaurantId == id).FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Restaurant edit = db.Restaurants.Find(id);
            if (edit == null)
            {
                return HttpNotFound();
            }
            return View(edit);
        }
        [HttpPost]
        public ActionResult Edit([Bind(Include = "RestaurantId,Name,Address,Phone,Picture,LocationId,PopularMenu,CostPerOrder,Time,Cuisine,Extra,Discount,UserName,Password")] Restaurant restaurant)
        {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
        }

        public ActionResult RestaurantReviewList(int? id, int? page)
        {
            if (Session["RestaurantsId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            id = Convert.ToInt32(Session["RestaurantsId"]);

            return View(db.Reviews.Where(x => x.RestaurantsId == id).ToList().ToPagedList(page ?? 1, 5));

        }

DBrms/Views/Restaurants/Details.cshtml
@model DBrms.Models.Restaurant

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_RestaurantLayout.cshtml";
}

<h2>Details of "@Model.Name"</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            <img src="@Model.Picture" height="200" width="400" />

        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PopularMenu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PopularMenu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuisine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

    </dl>
</div>


<div>
    <dl class="dl-horizontal">
       
        <center><p style="font-size:20px">@Html.ActionLink("Edit", "Edit", new { id = Model.RestaurantId })</p><center/>
</dl>

</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DBrms/Views/Restaurants/Edit.cshtml
@model DBrms.Models.Restaurant

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_RestaurantLayout.cshtml";
}

<h2>Edit</h2>
<link rel="stylesheet" href="~/Content/Login/dist/css/site.min.css">

<div class="container-fluid" style="font-size:13px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
        
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <input type="hidden" name="RestaurantId" id="RestaurantId" value="@Model.RestaurantId" />
            <input type="hidden" name="LocationId" id="LocationId" value="@Model.LocationId" />

            <input type="hidden" name="Picture" id="Picture" value="@Model.Picture" />

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Name" required value="@Model.Name" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                     <input class="form-control" type="text" name="Address" required value="@Model.Address" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Phone" pattern="\+?(88)?01[3456789][0-9]{8}\b" required value="@Model.Phone" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <img src="@Model.Picture" height="200" width="400" />
                   
                   
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("LocationId", null, "--Select One Location--", htmlAttributes: new { @class = "from-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PopularMenu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="PopularMenu" required value="@Model.PopularMenu" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CostPerOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="CostPerOrder" required value="@Model.CostPerOrder" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Time" required value="@Model.Time" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cuisine, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Cuisine" required value="@Model.Cuisine" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Extra, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Extra" required value="@Model.Extra" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Discount" required value="@Model.Discount" />
                </div>
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                 <div class="col-md-5">
                     <input class="form-control" type="text" name="Username" required value="@Model.Username" />
                 </div>
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                 <div class="col-md-5">
                     <input class="form-control" type="Password" name="Password" required value="@Model.Password" />
                 </div>
            </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

DBrms/Views/Restaurants/FoodReviewList.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<DBrms.Models.ReviewFood>

@{
    ViewBag.Title = "FoodReviewList";
    Layout = "~/Views/Shared/_RestaurantLayout.cshtml";
}


<input type="button" onclick="printDiv('printableArea')" value="Print" />
<div id="printableArea">
    <h2>Food Review List</h2>
    <table class="table">
        <tr>

            <th style="width:220px; padding-left:100px">
                Customer @Html.DisplayNameFor(model => model.First().Customer.Name)
            </th>
            <th style="width:150px">
                Customer @Html.DisplayNameFor(model => model.First().Customer.Image)
            </th>
            <th style="width:100px">
                Customer @Html.DisplayNameFor(model => model.First().Customer.Address)
            </th>
            <th style="width:100px">
                Food @Html.DisplayNameFor(model => model.First().Food.Name)
            </th>
            <th style="width:150px">
                Food @Html.DisplayNameFor(model => model.First().Food.Image)
            </th>
            <th style="width:300px">
                @Html.DisplayNameFor(model => model.First().Description)
            </th>
            <th style="width:120px">
                @Html.DisplayNameFor(model => model.First().RatingFood)
            </th>
            <th></th>
        </tr>
        @if (Model.Count == 0)
        {
            <center><p style="font-size:50px; color:crimson"> No review yet</p></center>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>


                    <td style="padding-left:100px">
                        @Html.DisplayFor(modelItem => item.Customer.Name)
                    </td>
                    <td>
                        <img src="@item.Customer.Image" height="80" width="120" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Food.Name)
                    </td>
                    <td>
                        <img src="@item.Food.Image" height="60" width="120" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @{

                            for (int i = 1; i <= item.RatingFood; i++)
                            {
                                <a>
                                    <img src="~/Image/Star-Full.png" height="15" width="15" />
                                </a>
                            }

                            var fau1 = item.RatingFood % 1;
                            if (fau1 == .5)
                            {
                                <a>
                                    <img src="~/Image/Star half.png" height="15" width="15" />
                                </a>
                            }


                        }
                    </td>
                </tr>
            }
        }

    </table>

    @Html.PagedListPager(Model, page => Url.Action("FoodReviewList", new { page }))
    </div>

DBrms/Views/Restaurants/Menu.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<DBrms.Models.Food>

@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_RestaurantLayout.cshtml";
}
<input type="button" onclick="printDiv('printableArea')" value="Print" />
<div id="printableArea">
    <div>
        @foreach (var item in ViewBag.Restaurants)
        {
            <h2>Menu of @item.Name</h2>
        }
    </div>
    <form action="" method="post" style="padding-left:800px">
        <input type="search" placeholder="Find Menu...." name="search" required="">
        <input type="submit" value="Search">
    </form>
    <p style="font-size:20px">
        @Html.ActionLink("Add Menu", "MenuAdd")
    </p>
    <table class="table">
        <tr>
            <th style=" padding-left:100px; width:140px;">
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
            <th style="width:150px">
                @Html.DisplayNameFor(model => model.First().Image)
            </th>
            <th style="width:80px">
                @Html.DisplayNameFor(model => model.First().Price)
            </th>
            <th style="width:300px">
                @Html.DisplayNameFor(model => model.First().Details)
            </th>

            <th style="width:200px"></th>
        </tr>

        @foreach (var item in Model)
        {
            using (Html.BeginForm("MenuDelete", "Restaurants", new { id = item.FoodId }))
            {
                <tr>
                    <td style=" padding-left:100px;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <img src="@item.Image" height="100" width="200" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)tk
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Details)
                    </td>

                    <td>
                        <p style="font-size:17px">
                            @Html.ActionLink("Edit", "MenuEdit", new { id = item.FoodId })|
                            <input type="submit" value="Delete" style="font-size:15px" onclick="return confirm('Are you sure? You want to delete?')" />
                        </p>

                    </td>
                </tr>
            }
        }

    </table>

    @Html.PagedListPager(Model, page => Url.Action("Menu", new { page }))
    </div>

DBrms/Views/Restaurants/MenuAdd.cshtml
@model DBrms.Models.Food

@{
    ViewBag.Title = "MenuAdd";
    Layout = "~/Views/Shared/_RestaurantLayout.cshtml";
}

<h2>Add Menu</h2>
<link rel="stylesheet" href="~/Content/Login/dist/css/site.min.css">

<div class="container-fluid" style="font-size:13px">
    @using (Html.BeginForm("MenuAdd", "Restaurants", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })



            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Name" required />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input type="file" id="ImageFile" name="ImageFile" required />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input class="form-control" type="text" name="Price" required />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
           
                    <textarea class="form-control" name="Details" required style="height:100px"></textarea>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>