DBrms/Models/Extended/Magazine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DBrms.Models.Extended
{
    [MetadataType(typeof(MetadataMagazine))]

    public partial class Magazine
    {
    }

    public class MetadataMagazine
    {
       
        [Required]
        public string Name { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Details { get; set; }
      
        public Nullable<bool> IsActive { get; set; }
    }
}

DBrms/Models/Extended/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DBrms.Models.Extended
{
    [MetadataType(typeof(MetadataRestaurant))]

    public partial class Restaurant
    {


    }

    public class MetadataRestaurant
        {
        
        
        [Required(ErrorMessage = "Enter Name")]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Picture { get; set; }
        [Required]
        public Nullable<int> LocationId { get; set; }
        [Required]
        public string PopularMenu { get; set; }
        [Required]
        [DisplayName("Cost Range")]
        public string CostPerOrder { get; set; }
        [Required]
        public string Time { get; set; }
        [Required]
        public string Cuisine { get; set; }
        [Required]
        public string Extra { get; set; }
        [Required]
        public string Discount { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
  
        public Nullable<bool> IsActive { get; set; }
 
        public Nullable<bool> Visible { get; set; }
    }

}

DBrms/Models/Magazine.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Magazine
    {
        public int MagazineId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        [DisplayName("Active")]
        public Nullable<bool> IsActive { get; set; }
    }
}

DBrms/Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Foods = new HashSet<Food>();
            this.Reviews = new HashSet<Review>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Picture { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string PopularMenu { get; set; }
        [DisplayName("Cost Range")]
        public string CostPerOrder { get; set; }
        public string Time { get; set; }
        public string Cuisine { get; set; }
        public string Extra { get; set; }
        public string Discount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        [DisplayName("Active")]
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
        public virtual FoodOrder FoodOrder { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

DBrms/Controllers/WebsiteController.cs
using DBrms.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace DBrms.Controllers
{
    public class WebsiteController : Controller
    {
        dbrmsEntities db = new dbrmsEntities();
        // GET: Website
        public ActionResult Index()
        {
            List<Slider> sliders = db.Sliders.Where(x => x.IsActive == true).ToList();
            ViewBag.Sliders = sliders;

            List<Review> reviews = db.Reviews.Where(x => x.IsActive == true).ToList();
            ViewBag.Reviews = reviews;

            List<Magazine> magazines = db.Magazines.Where(x => x.IsActive == true).ToList();
            ViewBag.Magazines = magazines;

            List<Restaurant> restaurants = db.Restaurants.Where(x => x.IsActive == true).ToList();
            ViewBag.Restaurants = restaurants;

            List<ReviewFood> reviewFoods = db.ReviewFoods.Where(x => x.IsActive == true).ToList();
            ViewBag.ReviewFoods = reviewFoods;

            return View();
        }
        public ActionResult Magazine(int? page)
        {

            var magazines = db.Magazines.ToList().ToPagedList(page ?? 1, 9);
            ViewBag.Magazines = magazines;


            return View(magazines);
        }


        public ActionResult MagazineSingle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Magazine magazine = db.Magazines.Find(id);
            ViewBag.Magazines = magazine;
            if (magazine == null)
            {
                return HttpNotFound();
            }
            return View(magazine);
        }

        public ActionResult ContactUs()
        {



            return View();
        }



        public ActionResult Restaurants(int? page, string search, string range, string discount, string id)
        {
            if (search != null && range == null && discount == null)
            {
                return View(db.Restaurants.Where(x => x.Name.StartsWith(search)).ToList().ToPagedList(page ?? 1, 3));
            }
            if (range == "400-499")
            {

                var range1 = db.Restaurants.Where(x => x.CostPerOrder.Contains("400")).ToList().ToPagedList(page ?? 1, 3);
                return View(range1);
            }
            if (range == "300-399")
            {

                var range2 = db.Restaurants.Where(x => x.CostPerOrder.Contains("300")).ToList().ToPagedList(page ?? 1, 3);
                return View(range2);
            }
            if (range == "200-299")
            {

                var range3 = db.Restaurants.Where(x => x.CostPerOrder.Contains("200")).ToList().ToPagedList(page ?? 1, 3);
                return View(range3);
            }
            if (range == "100-199")
            {
                var range4 = db.Restaurants.Where(x => x.CostPerOrder.Contains("100")).ToList().ToPagedList(page ?? 1, 3);
                return View(range4);
            }

            //Logic for Discount
            //Logic for Discount

            if (discount == "5" && range == null)
            {
                var discount1 = db.Restaurants.Where(x => x.Discount.StartsWith("5")).ToList().ToPagedList(page ?? 1, 3);
                return View(discount1);
            }
            if (discount == "10" && range == null)
            {
                var discount2 = db.Restaurants.Where(x => x.Discount.Contains("10")).ToList().ToPagedList(page ?? 1, 3);
                return View(discount2);
            }
            if (discount == "15" && range == null)
            {
                var discount3 = db.Restaurants.Where(x => x.Discount.Contains("15")).ToList().ToPagedList(page ?? 1, 3);
                return View(discount3);
            }

            //logic for Loaction
            //logic for Loaction



            var restaurants = db.Restaurants.ToList().ToPagedList(page ?? 1, 5);
            ViewBag.Restaurants = restaurants;

            return View(restaurants);
        }

        public ActionResult RestaurantsLocation(string id, int? page)
        {
            if (id == "Uttara")
            {
                var location1 = db.Restaurants.Where(x => x.LocationId == 1).ToList().ToPagedList(page ?? 1, 3);
                return View(location1);
            }
            if (id == "Mirpur")
            {
                var location2 = db.Restaurants.Where(x => x.LocationId == 2).ToList().ToPagedList(page ?? 1, 3);
                return View(location2);
            }
            if (id == "Dhanmondi")
            {
                var location3 = db.Restaurants.Where(x => x.LocationId == 3).ToList().ToPagedList(page ?? 1, 3);
                return View(location3);
            }
            if (id == "300 Feet")
            {
                var location4 = db.Restaurants.Where(x => x.LocationId == 4).ToList().ToPagedList(page ?? 1, 3);
                return View(location4);
            }
            if (id == "Banani")
            {
                var location5 = db.Restaurants.Where(x => x.LocationId == 5).ToList().ToPagedList(page ?? 1, 3);
                return View(location5);
            }
            if (id == "Basundhara R area")
            {
                var location6 = db.Restaurants.Where(x => x.LocationId == 6).ToList().ToPagedList(page ?? 1, 3);
                return View(location6);
            }
            if (id == "Mohammad Pur")
            {
                var location7 = db.Restaurants.Where(x => x.LocationId == 7).ToList().ToPagedList(page ?? 1, 3);
                return View(location7);
            }
            if (id == "Gulsan-1")
            {
                var location8 = db.Restaurants.Where(x => x.LocationId == 8).ToList().ToPagedList(page ?? 1, 3);
                return View(location8);
            }
            if (id == "Gulsan-2")
            {
                var location9 = db.Restaurants.Where(x => x.LocationId == 9).ToList().ToPagedList(page ?? 1, 3);
                return View(location9);
            }
            if (id == "Jamuna Future Park")
            {
                var location10 = db.Restaurants.Where(x => x.LocationId == 10).ToList().ToPagedList(page ?? 1, 3);
                return View(location10);
            }
            if (id == "Basundhara City")
            {
                var location11 = db.Restaurants.Where(x => x.LocationId == 11).ToList().ToPagedList(page ?? 1, 3);
                return View(location11);
            }
            var restaurants = db.Restaurants.ToList().ToPagedList(page ?? 1, 5);
            ViewBag.Restaurants = restaurants;
            return View(restaurants);
        }

        [HttpGet]
        public ActionResult RestaurantProfile(int? id)
        {
            List<Review> reviews = db.Reviews.Where(x => x.RestaurantsId == id).ToList();
            ViewBag.Reviews = reviews;

            List<Food> foods = db.Foods.Where(x => x.RestaurantId == id).ToList();

            ViewBag.Foods = foods;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }





            return View(restaurant);


        }
        [HttpPost]
        public ActionResult RestaurantProfile(int RestaurantId, string Description, string Rating )
        {
            Review review = new Review();
            if (Session["CustomerId"] != null)
            {
                int id = Convert.ToInt32(Session["CustomerId"]);
                review.CustomerId = id;

                if(Rating == "1")
                {
                    int rat = 1;
                    review.Rating = rat;
                }
                if (Rating == "2")
                {
                    int rat = 2;
                    review.Rating = rat;
                }
                if (Rating == "3")
                {
                    int rat = 3;
                    review.Rating = rat;
                }
                if (Rating == "4")
                {
                    int rat = 4;
                    review.Rating = rat;
                }
                if (Rating == "5")
                {
                    int rat = 5;
                    review.Rating = rat;
                }

                review.RestaurantsId = RestaurantId;
                review.Description = Description;
                review.Date = DateTime.Now;

                if (ModelState.IsValid)
                {
                    db.Reviews.Add(review);
                    db.SaveChanges();
                    ModelState.Clear();
                    return RedirectToAction("RestaurantProfile");
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        [HttpGet]
        public ActionResult FoodSingle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            List<ReviewFood> reviewFoods = db.ReviewFoods.Where(x => x.FoodId == id).ToList();
            ViewBag.ReviewFoods = reviewFoods;


            return View(food);
        }

        [HttpPost]
        public ActionResult FoodSingle(int FoodId, string Description, string RatingFood)
        {
            ReviewFood reviewFood = new ReviewFood();
            if (Session["CustomerId"] != null)
            {

                int customerId = Convert.ToInt32(Session["CustomerId"]);

DBrms/Views/Website/CustomerRegistration.cshtml
@model DBrms.Models.Customer

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Customer Registration</title>
    <meta charset="utf-8">
   
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="favicon_16.ico" />
    <link rel="bookmark" href="favicon_16.ico" />
    <!-- site css -->
    <link rel="stylesheet" href="~/Content/Login/dist/css/site.min.css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,800,700,400italic,600italic,700italic,800italic,300italic" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="~/Content/Login/dist/js/site.min.js"></script>
    <style>


        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-image: url('../../Image/login-background.jpg');
            background-position: center;
            background-size:auto;
            color: #2c2d2d
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="form-signin">
            @using (Html.BeginForm("CustomerRegistration", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Customer Registration</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="ImageFile" name="ImageFile" required />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
</body>
</html>

DBrms/Views/Website/RestaurantRegistration.cshtml
@model DBrms.Models.Restaurant

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Restaurant Registration</title>
    <meta charset="utf-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="favicon_16.ico" />
    <link rel="bookmark" href="favicon_16.ico" />
    <!-- site css -->
    <link rel="stylesheet" href="~/Content/Login/dist/css/site.min.css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,800,700,400italic,600italic,700italic,800italic,300italic" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="~/Content/Login/dist/js/site.min.js"></script>
    <style>


        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-image: url('../../Image/login-background.jpg');
            background-position: center;
            background-size:cover;
            color: #2c2d2d
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="form-signin" style="font-size:13px;">
            @using (Html.BeginForm("RestaurantRegistration", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4 style="color:darkolivegreen">Restaurant Registration</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="ImageFile" name="ImageFile" required />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LocationId, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">

                            @Html.DropDownList("LocationId", null, "--Select One Location--", htmlAttributes: new { @class = "from-control" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.CostPerOrder,"Cost Range", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CostPerOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CostPerOrder, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cuisine, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cuisine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cuisine, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>